language: ruby
rvm: 2.2.4
script: bundle exec rake test
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- psql -c 'create database mightysmallsprod_test;' -U postgres
before_script:
- bundle exec rake db:migrate RAILS_ENV=test
deploy:
  provider: heroku
  api_key:
    secure: UCGqizQrm7aJWQOoISmb4rL4+LUW4ZucC88IWNSEJ3L2saQbDDiSip2E8VUYUpQSwjhLZXkZC6ta+ZD7zcbpVLlHF03pI3JAvnuKsdS2XQ4qoWrIez8Fh20nWY3+Z+9/OqEowVhRytWCpEi2xMj1OFBFiSUaxlmXqRBV0PgI+QDOhSCDLbbcLGKgWCaAsqVioc/xqz1PfipLdpALbkRP3PLCrmXuK0STPjmemDGvJw99SDu4C87XHulsuxMcabg94NfX4F5yIj1RVhfFRO4fV99Tu1OP8cvj6yymhJo4wzfQxJqXTB8fCpMz/w6tAbXVPtezII/uHu1Z8YQCAB0VZjcVpsuCzKD4VFgx4zbrDvI6mFOK/VVEubtmhDWn86uKUrLR0z1u3L47BSjf1jg5+nSUVUsKV6bEorLTXl8S5WXa/F1DDg4VzJIifN6f9erpANMJwo0fT74VWxdvxHBSMgbH7lvSa+2/7PigTWyHW+QpZaiJX6EKdASt9jw1irhdNqH5mvAaqtLbq8jzUJkE+RJXMP19XHVZTHHx1a1YA/xj7kD5OYcbAHVWWmwQYl6hTC/aLmw2ut100Rsyu6JTSviGseeqmTUp3pwkQjaDaTQBPG9vPM9A5rCUINtBBSk9oDgGqONp2F4NeISPFp8NTPY5wFUEvx3qDKPqsmrhpKc=
  app: mightysmallsprod
  on:
    repo: hail2skins/mightyprod
