development:
  adapter: postgresql
  encoding: unicode
  database: mightysmallsprod_development
  pool: 5
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: mightysmallsprod_test
  pool: 5
  template: template0